### ISSUE TITLE
No Access Point available (A6210, ElementaryOS 0.4.1)

### ISSUE THREAD

**Issue by mickaelandrieu** [jurobystricky/Netgear-A6210#71]
Hello,

I could install your drivers with success, and now I see a "Wireless" network available, but I can't find any Access Point available.

So you have any idea? Thank you for your help :)

Mickaël

**Comment by GrayBoltWolf** [comment]
Same issue here. Debian Stretch, kernel 4.9.

Adapter works and network manager sees it, but it doesn't find any access points.

**Comment by genodeftest** [comment]
Which hardware are you using?

**Comment by mickaelandrieu** [comment]
Sorry I've buyed another wifi usb key.
