### ISSUE TITLE
Netgear-A6210 will not compile on Debian Stretch

### ISSUE THREAD

**Issue by rmarcks** [jurobystricky/Netgear-A6210#76]
I have downloaded the source code for Netgear-A6210 and have not been able to successfully compile on Debian Stretch. The output of the make command is:

******************************************************************************************************
russell@debian:~/Netgear-A6210$ sudo make
[sudo] password for russell: 
export DBGFLAGS

*** Building driver with debug messages ***

cp -f os/linux/Makefile.6 /home/russell/Netgear-A6210/os/linux/Makefile
make -C /lib/modules/4.9.0-3-amd64/build DBGFLAGS=-DDBG SUBDIRS=/home/russell/Netgear-A6210/os/linux modules
make[1]: *** /lib/modules/4.9.0-3-amd64/build: No such file or directory.  Stop.
Makefile:59: recipe for target 'debug' failed
make: *** [debug] Error 2
******************************************************************************************************
Need some expertise from the experts.

Thanks
RKM
(Russell Marcks)

**Comment by pholtz** [comment]
I had a similar error, which I was able to resolve by downloading the amd64 linux headers through apt. Try:

`sudo apt list linux-headers*`

to see a list of options and then install the correct one. In your case, i'm assuming this would be 4.9.0.3-amd64. HTH.

**Comment by rmarcks** [comment]
Well...for a moment I thought that was the problem.  I installed the headers, ran make, the make process was going along quite nicely, then it stopped with an error.  The make command now returns:

********************************************************************************************************************
export DBGFLAGS

*** Building driver with debug messages ***

cp -f os/linux/Makefile.6 /home/russell/Downloads/Netgear-A6210-master/os/linux/Makefile
make -C /lib/modules/4.9.0-3-amd64/build DBGFLAGS=-DDBG SUBDIRS=/home/russell/Downloads/Netgear-A6210-master/os/linux modules
make[1]: Entering directory '/usr/src/linux-headers-4.9.0-3-amd64'
make[4]: *** No rule to make target '/home/russell/Downloads/Netgear-A6210-master/os/linux/../../tx_rx/wdev_tx.o', needed by '/home/russell/Downloads/Netgear-A6210-master/os/linux/mt7662u_sta.o'.  Stop.
/usr/src/linux-headers-4.9.0-3-common/Makefile:1507: recipe for target '_module_/home/russell/Downloads/Netgear-A6210-master/os/linux' failed
make[3]: *** [_module_/home/russell/Downloads/Netgear-A6210-master/os/linux] Error 2
Makefile:150: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.9.0-3-amd64'
Makefile:59: recipe for target 'debug' failed
make: *** [debug] Error 2
********************************************************************************************************************

I tried to research similar threads on this site, but to no avail.  Since I'm not a programmer, the ***No rule to make target... had me baffled.  

Any additional help is appreciated.

RKM

**Comment by rmarcks** [comment]
OK....I checked the directory /home/russell/Downloads/Netgear-A6210-master/os/linux/../../tx_rx/ for the file wdev_tx.o and it indeed does not exist as indicated in the error message above.  A search for wdev_tx.o gives me two listings of the file wdev_tx.c on github.com and one by the same name over at code.aliyun.com.  I'm not anxious to arbitrarily copy and paste these contents into a file and place it into the correct directory without confirmation of which of the three to use (if any), how to use it, and whether or not this is the correct approach.

Again....I'm not a programmer and have no clue the contents of these three files and what they are doing; but it does seem the correct thing to do!?

Thanks
RKM

**Comment by rmarcks** [comment]
Ooops again....what I found was wdev_tx.c NOT wdev_tx.o

RKM
