### ISSUE TITLE
Compilation problem with kali linux

### ISSUE THREAD

**Issue by Swelio** [jurobystricky/Netgear-A6210#79]
Hi,
I've tried to install the driver on my kali linux system

But as you can see, I have got an error 2, I've searched what it can be and I didn't found anything.

The system is freshly installed.

System : 
`# uname -r
4.12.0-kali1-amd64
`

**Comment by genodeftest** [comment]
Please have a look at existing bug reports before opening new ones. This bug report looks like a duplicate of #78 to me. 

Anyway, can you try the changes I suggested in #77? I haven't tested these on hardware, but at least they made the module build again. Please report back if they make your hardware work, preferably as a comment to #77. If it fixes your build problem, please close this bug report.

PS: Please do not paste code directly into the comment field, but use code blocks, which increases readability a lot. If you don't, you just waste developer resources.
