### ISSUE TITLE
Compilation error with make - cfg80211.c

### ISSUE THREAD

**Issue by aaronanglade** [jurobystricky/Netgear-A6210#9]
Hi,

Make failed 

../os/linux/cfg80211/cfg80211.c: In function CFG80211_OpsStaDel
../os/linux/cfg80211/cfg80211.c: 2112:6 : error pMacAddr undeclared (first use in this function)
     if (pMacAddr == NULL) {

**Comment by jurobystricky** [comment]
Hmm, I pushed a fix for this few hours ago. ..
There are various Linux kernel versions involved...
So what is your kernel version?

In any case please change the line 2106 from
#if (LINUX_VERSION_CODE >= KERNEL_VERSION(4,2,0))
to
#if (LINUX_VERSION_CODE >= KERNEL_VERSION(3,19,0))

**Comment by aaronanglade** [comment]
Thanks for quick reply

My kernel version : 4.1.19-v7+ #852 SMP armv7

**Comment by aaronanglade** [comment]
I tested. Compilation is ok. I change only the kernel version. Installation is ok.
Now i configure ;-)

Thanks again
